<?php
?>
<table cellspacing="0">
    <tr>
        <td><?php echo $this->getIcon($this->phpVersion) ?></td>
        <td><?php echo $this->__("PHP Version") ?></td>
        <td>
            <?php echo $this->getPhpVersion() ?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->getIcon($this->memory) ?></td>
        <td><?php echo $this->__("Max Memory") ?></td>
        <td>
            <?php echo $this->getMemory() ?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->getIcon($this->credentials) ?></td>
        <td><?php echo $this->__("Credentials") ?></td>
        <td>
            <?php echo $this->getCredentials() ?>
        </td>
    </tr>
    <tr>
        <td><?php echo "<a target='_blank' href='https://help.cobby.io'>" . $this->__("Need help?") . "</a>" ?></td>
    </tr>
</table>
