<?php
?>
<table cellspacing="0">
    <tr>
        <td><?php echo $this->getIcon($this->phpVersion) ?></td>
        <td><?php echo $this->__("PHP Version") ?></td>
        <td>
            <?php echo $this->getPhpVersion() ?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->getIcon($this->memory) ?></td>
        <td><?php echo $this->__("Max Memory") ?></td>
        <td>
            <?php echo $this->getMemory() ?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->getIcon($this->credentials) ?></td>
        <td><?php echo $this->__("Credentials") ?></td>
        <td>
            <?php echo $this->getCredentials() ?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->getIcon($this->maintenance)?></td>
        <td><?php echo $this->__("Maintenance Mode")?></td>
        <td>
            <?php echo $this->getMaintenanceMode()?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->getIcon($this->indexer)?></td>
        <td><?php echo $this->__("Indexer")?></td>
        <td>
            <?php echo $this->getIndexerStatus()?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->getIcon($this->url)?></td>
        <td><?php echo $this->__("Url Check")?></td>
        <td>
            <?php echo $this->getUrlCheck()?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->getIcon($this->cobbyActive)?></td>
        <td><?php echo $this->__("Cobby active")?></td>
        <td>
            <?php echo $this->getCobbyActive()?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->getIcon($this->cobbyVersion)?></td>
        <td><?php echo $this->__("Cobby version")?></td>
        <td><?php echo $this->getCobbyVersion()?></td>
    </tr>
    <tr>
        <td><?php echo "<a target='_blank' href='https://help.cobby.io'>" . $this->__("Need help?") . "</a>" ?></td>
    </tr>
</table>
